#!/usr/bin/env bash
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Runs the self-checking test of the Dynamatic flow's dot_product_hls_adapter
# (with the Dynamatic-generated circuit and the shared CTRL register file)
# with Verilator (>= 5, for --binary/--timing). Prints
# "dot_product_adapter_tb: PASS" on success and exits non-zero on failure.
#
# The circuit is generated first if needed (../generate_core.sh: Dynamatic in
# Docker, or DYNAMATIC_DIR=...). The rest needs what any X-HEEP FuseSoC build
# needs (the fusesoc and regtool Python dependencies, see
# util/python-requirements.txt), because the register file is generated by
# regtool.
#
#   hw/fpga/hls/dynamatic/dot_product/tb/run.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XHEEP_ROOT="$(cd "$SCRIPT_DIR/../../../../../.." && pwd)"

"$SCRIPT_DIR/../generate_core.sh"

# Same default as the top-level Makefile.
export REGTOOL="${REGTOOL:-$XHEEP_ROOT/hw/vendor/pulp_platform/register_interface/vendor/lowrisc_opentitan/util/regtool.py}"

BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

cd "$XHEEP_ROOT"
# Let FuseSoC resolve the dependencies and run regtool; we only need the list
# of sources it produces (a Verilator command file), not its own build.
fusesoc --cores-root . run --no-export --target=sim --tool=verilator \
  --build-root "$BUILD_DIR" --setup epfl:ip:dot_product_dynamatic_tb \
  >"$BUILD_DIR/fusesoc.log" 2>&1 || {
  cat "$BUILD_DIR/fusesoc.log"
  exit 1
}

VC="$(ls "$BUILD_DIR"/*/*.vc)"
# The paths in the command file are relative to its own directory.
cd "$(dirname "$VC")"
verilator --binary --timing --sv -Wno-fatal -Wno-lint -Wno-style \
  -f "$VC" --Mdir "$BUILD_DIR/obj" >"$BUILD_DIR/verilator.log" 2>&1 || {
  cat "$BUILD_DIR/verilator.log"
  exit 1
}

OUT="$("$BUILD_DIR/obj/Vdot_product_adapter_tb")"
echo "$OUT"
echo "$OUT" | grep -q "dot_product_adapter_tb: PASS"
