// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module camera_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 4
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,

    // Output port for window
    output reg_req_t [1-1:0] reg_req_win_o,
    input  reg_rsp_t [1-1:0] reg_rsp_win_i,

    // To HW
    output camera_reg_pkg::camera_reg2hw_t reg2hw,  // Write
    input  camera_reg_pkg::camera_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import camera_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic               reg_we;
  logic               reg_re;
  logic [BlockAw-1:0] reg_addr;
  logic [     DW-1:0] reg_wdata;
  logic [    DBW-1:0] reg_be;
  logic [     DW-1:0] reg_rdata;
  logic               reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  logic [0:0] reg_steer;

  reg_req_t [2-1:0] reg_intf_demux_req;
  reg_rsp_t [2-1:0] reg_intf_demux_rsp;

  // demux connection
  assign reg_intf_req = reg_intf_demux_req[1];
  assign reg_intf_demux_rsp[1] = reg_intf_rsp;

  assign reg_req_win_o[0] = reg_intf_demux_req[0];
  assign reg_intf_demux_rsp[0] = reg_rsp_win_i[0];

  // Create Socket_1n
  reg_demux #(
      .NoPorts(2),
      .req_t  (reg_req_t),
      .rsp_t  (reg_rsp_t)
  ) i_reg_demux (
      .clk_i,
      .rst_ni,
      .in_req_i(reg_req_i),
      .in_rsp_o(reg_rsp_o),
      .out_req_o(reg_intf_demux_req),
      .out_rsp_i(reg_intf_demux_rsp),
      .in_select_i(reg_steer)
  );


  // Create steering logic
  always_comb begin
    reg_steer = 1;  // Default set to register

    // TODO: Can below codes be unique case () inside ?
    if (reg_req_i.addr[AW-1:0] >= 8 && reg_req_i.addr[AW-1:0] < 12) begin
      reg_steer = 0;
    end
  end


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic control_start_qs;
  logic control_start_wd;
  logic control_start_we;
  logic control_pwnd_qs;
  logic control_pwnd_wd;
  logic control_pwnd_we;
  logic control_reset_qs;
  logic control_reset_wd;
  logic control_reset_we;
  logic status_qs;

  // Register instances
  // R[control]: V(False)

  //   F[start]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_start (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_start_we),
      .wd(control_start_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.start.q),

      // to register interface (read)
      .qs(control_start_qs)
  );


  //   F[pwnd]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_pwnd (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_pwnd_we),
      .wd(control_pwnd_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.pwnd.q),

      // to register interface (read)
      .qs(control_pwnd_qs)
  );


  //   F[reset]: 2:2
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_reset (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_reset_we),
      .wd(control_reset_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.reset.q),

      // to register interface (read)
      .qs(control_reset_qs)
  );


  // R[status]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.status.de),
      .d (hw2reg.status.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.status.q),

      // to register interface (read)
      .qs(status_qs)
  );




  logic [1:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == CAMERA_CONTROL_OFFSET);
    addr_hit[1] = (reg_addr == CAMERA_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(CAMERA_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(CAMERA_PERMIT[1] & ~reg_be)))));
  end

  assign control_start_we = addr_hit[0] & reg_we & !reg_error;
  assign control_start_wd = reg_wdata[0];

  assign control_pwnd_we  = addr_hit[0] & reg_we & !reg_error;
  assign control_pwnd_wd  = reg_wdata[1];

  assign control_reset_we = addr_hit[0] & reg_we & !reg_error;
  assign control_reset_wd = reg_wdata[2];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = control_start_qs;
        reg_rdata_next[1] = control_pwnd_qs;
        reg_rdata_next[2] = control_reset_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module camera_reg_top_intf #(
    parameter  int AW = 4,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    REG_BUS.out regbus_win_mst[1-1:0],
    // To HW
    output camera_reg_pkg::camera_reg2hw_t reg2hw,  // Write
    input camera_reg_pkg::camera_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  reg_bus_req_t s_reg_win_req[1-1:0];
  reg_bus_rsp_t s_reg_win_rsp[1-1:0];
  for (genvar i = 0; i < 1; i++) begin : gen_assign_window_structs
    `REG_BUS_ASSIGN_TO_REQ(s_reg_win_req[i], regbus_win_mst[i])
    `REG_BUS_ASSIGN_FROM_RSP(regbus_win_mst[i], s_reg_win_rsp[i])
  end



  camera_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg_req_win_o(s_reg_win_req),
      .reg_rsp_win_i(s_reg_win_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


