# Copyright 2026 contributors
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

proc xheep_generate_core_clk_period_xdc {out_clk_freq_MHz board_script_path} {
  set project_dir [get_property DIRECTORY [current_project]]
  set constrs_fileset [get_filesets constrs_1]
  set generated_xdc [file join $project_dir xheep_core_clk_period.xdc]

  set fd [open $generated_xdc w]
  puts $fd "### Auto-generated by [file tail $board_script_path]"
  puts $fd [format {set xheep_core_clk_period_ns %.12g} [expr {1000.0 / double($out_clk_freq_MHz)}]]
  close $fd

  if {[llength [get_files -quiet -of_objects $constrs_fileset $generated_xdc]] == 0} {
    add_files -norecurse -fileset $constrs_fileset $generated_xdc
  }

  set common_dir [file normalize [file join [file dirname $board_script_path] .. .. constraints common]]
  set jtag_xdc [get_files -quiet -of_objects $constrs_fileset [file join $common_dir jtag.xdc]]
  if {[llength $jtag_xdc] > 0} {
    reorder_files -fileset $constrs_fileset -before $jtag_xdc $generated_xdc
  }
}
