#ifndef XHEEP_TRANSFORMER_FFT_PARAM_H
#define XHEEP_TRANSFORMER_FFT_PARAM_H

#define USE_FPU 1u
#define CONTINUE_RUN 0u
#define USE_P2P 0u
#define CONTINUE_RUN_PROFILE 1u
#define CONTINUE_RUN_CHECK_RESULT 1u
#define CONTINUE_RUN_DEBUG 1u
#if CONTINUE_RUN
#undef USE_P2P
#define USE_P2P 0u
#undef CONTINUE_RUN_PROFILE
#undef CONTINUE_RUN_CHECK_RESULT
#undef CONTINUE_RUN_DEBUG
#define CONTINUE_RUN_PROFILE 0u
#define CONTINUE_RUN_CHECK_RESULT 0u
#define CONTINUE_RUN_DEBUG 0u
#endif

#endif
