# Copyright (c) 2011-2024 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
ACCEL_NAME ?= xheep

APPNAME := esp_heep_p2p_dma
APP_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
CFLAGS += -I$(APP_PATH)common -I$(APP_PATH)include
include $(DRIVERS)/common_bare.mk
