#!/usr/bin/env bash
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Runs Vitis HLS synthesis for the dot_product engine, copies the generated
# RTL into rtl/hls/, and (re)generates dot_product.core listing it -- so
# `make verilator-build` / `make vivado-fpga` can pick it up via FuseSoC.
#
# Usage:
#   source <vivado_install>/settings64.sh
#   source <vitis_hls_install>/settings64.sh
#   ./generate_core.sh
#
# Skips re-running Vitis HLS (and therefore doesn't need it installed) if
# rtl/hls/ already holds RTL newer than every input that could affect it.
# Pass FORCE=1 to regenerate unconditionally.
#
# ./generate_core.sh clean
#   Removes the generated artifacts: the Vitis HLS project and rtl/hls/.
#   Does not need vitis_hls installed. Does NOT remove dot_product.core --
#   that file is committed to git (unlike rtl/hls/ and dot_product_proj/,
#   which are gitignored) because FuseSoC needs it to resolve
#   epfl:ip:dot_product as a dependency *before* it runs any pre_build
#   hook -- if it didn't exist at all, dependency resolution would fail
#   outright and the hook that (re)generates rtl/hls/ would never run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SELF="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
cd "$SCRIPT_DIR"

DST_DIR="rtl/hls"
CORE_FILE="dot_product.core"

if [ "${1:-}" = "clean" ]; then
  rm -rf dot_product_proj "$DST_DIR"
  echo "Removed dot_product_proj/ and $DST_DIR/."
  echo "$CORE_FILE was left untouched (it's committed to git, not generated)."
  exit 0
fi

if [ "${FORCE:-0}" != "1" ] && [ -f "$CORE_FILE" ] && [ -d "$DST_DIR" ] \
  && [ -n "$(find "$DST_DIR" -maxdepth 1 -name '*.v' -print -quit)" ]; then
  stale_src=$(find dot_product.cpp dot_product.h run_hls.tcl "$SELF" -newer "$CORE_FILE" 2>/dev/null | head -1)
  if [ -z "$stale_src" ]; then
    echo "dot_product RTL in $DST_DIR/ is already up to date (nothing changed since last generation) -- skipping Vitis HLS."
    echo "Set FORCE=1 to regenerate anyway."
    exit 0
  fi
fi

if ! command -v vitis_hls >/dev/null 2>&1; then
  echo "error: vitis_hls not found in PATH -- source Vivado's and Vitis HLS's settings64.sh first" >&2
  exit 1
fi

rm -rf dot_product_proj
vitis_hls -f run_hls.tcl

SYN_DIR="dot_product_proj/solution1/syn/verilog"
DST_DIR="rtl/hls"

if [ ! -d "$SYN_DIR" ]; then
  echo "error: HLS synthesis did not produce $SYN_DIR -- check hls_run.log" >&2
  exit 1
fi

mkdir -p "$DST_DIR"
rm -f "$DST_DIR"/*.v
cp "$SYN_DIR"/*.v "$DST_DIR"/

# Strip the per-file `timescale directive Vitis HLS emits: no other file in
# this project sets one (X-HEEP relies on Verilator's single implicit
# timescale), so leaving it in would make every other module in the whole
# design "inconsistent" in Verilator 5's eyes (TIMESCALEMOD warning) rather
# than just these few files.
sed -i '/^`timescale /d' "$DST_DIR"/*.v

HLS_FILES=$(cd "$DST_DIR" && ls *.v | sort | sed 's/^/    - rtl\/hls\//')

cat >dot_product.core <<EOF
CAPI=2:

# Auto-generated by generate_core.sh -- do not edit by hand.
# Regenerate with:
#   source <vivado_install>/settings64.sh && source <vitis_hls_install>/settings64.sh
#   ./generate_core.sh

name: "epfl:ip:dot_product"
description: "HLS-generated streaming dot-product accelerator, wrapped for X-HEEP OBI."

filesets:
  files_rtl:
    depend:
    - x-heep::packages
    - pulp-platform.org::obi
    - pulp-platform.org::axi
    - pulp-platform.org::axi_obi
    - x-heep:ip:xheep_obi_to_axi_bridge
    - x-heep:ip:xheep_axi_to_obi_bridge
    files:
$HLS_FILES
    - rtl/dot_product_xheep_wrapper.sv
    file_type: systemVerilogSource

  verilator-waiver:
    files:
    - dot_product.vlt
    file_type: vlt

targets:
  default:
    filesets:
    - files_rtl
    - tool_verilator ? (verilator-waiver)
EOF

n_files=$(echo "$HLS_FILES" | wc -l)
echo "Generated dot_product.core: ${n_files} HLS RTL file(s) + wrapper, from ${SYN_DIR}."
