add_subdirectory("./ams/")
add_subdirectory("./dlc/")
add_subdirectory("./iffifo/")
add_subdirectory("./gpio_cnt/")
add_subdirectory("./im2col_spc/")
add_subdirectory("./slow_memory/")
add_subdirectory("./pdm2pcm_dummy/")
add_subdirectory("./fpu_ss_wrapper/")
add_subdirectory("./i2s_microphone/")
add_subdirectory("./simple_accelerator/")
