add_ip_from_fusesoc("../vendor/xheep_i2s/i2s.core")
add_subdirectory(fast_intr_ctrl)
add_subdirectory(obi_fifo)
add_subdirectory(obi_spimemio)
add_subdirectory(soc_ctrl)
add_subdirectory(power_manager)
add_subdirectory(pdm2pcm)
add_subdirectory(dma_subsystem)
add_subdirectory(serial_link_xheep_wrapper)
add_subdirectory(w25q128jw_controller)
