// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module hdmi_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 5
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,

    // Output port for window
    output reg_req_t [1-1:0] reg_req_win_o,
    input  reg_rsp_t [1-1:0] reg_rsp_win_i,

    // To HW
    output hdmi_reg_pkg::hdmi_reg2hw_t reg2hw,  // Write
    input  hdmi_reg_pkg::hdmi_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import hdmi_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic               reg_we;
  logic               reg_re;
  logic [BlockAw-1:0] reg_addr;
  logic [     DW-1:0] reg_wdata;
  logic [    DBW-1:0] reg_be;
  logic [     DW-1:0] reg_rdata;
  logic               reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  logic [0:0] reg_steer;

  reg_req_t [2-1:0] reg_intf_demux_req;
  reg_rsp_t [2-1:0] reg_intf_demux_rsp;

  // demux connection
  assign reg_intf_req = reg_intf_demux_req[1];
  assign reg_intf_demux_rsp[1] = reg_intf_rsp;

  assign reg_req_win_o[0] = reg_intf_demux_req[0];
  assign reg_intf_demux_rsp[0] = reg_rsp_win_i[0];

  // Create Socket_1n
  reg_demux #(
      .NoPorts(2),
      .req_t  (reg_req_t),
      .rsp_t  (reg_rsp_t)
  ) i_reg_demux (
      .clk_i,
      .rst_ni,
      .in_req_i(reg_req_i),
      .in_rsp_o(reg_rsp_o),
      .out_req_o(reg_intf_demux_req),
      .out_rsp_i(reg_intf_demux_rsp),
      .in_select_i(reg_steer)
  );


  // Create steering logic
  always_comb begin
    reg_steer = 1;  // Default set to register

    // TODO: Can below codes be unique case () inside ?
    if (reg_req_i.addr[AW-1:0] >= 16 && reg_req_i.addr[AW-1:0] < 20) begin
      reg_steer = 0;
    end
  end


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_en_qs;
  logic ctrl_en_wd;
  logic ctrl_en_we;
  logic [2:0] ctrl_pattern_qs;
  logic [2:0] ctrl_pattern_wd;
  logic ctrl_pattern_we;
  logic [23:0] color_qs;
  logic [23:0] color_wd;
  logic color_we;
  logic status_qs;
  logic [31:0] frame_cnt_qs;

  // Register instances
  // R[ctrl]: V(False)

  //   F[en]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_ctrl_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ctrl_en_we),
      .wd(ctrl_en_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ctrl.en.q),

      // to register interface (read)
      .qs(ctrl_en_qs)
  );


  //   F[pattern]: 3:1
  prim_subreg #(
      .DW      (3),
      .SWACCESS("RW"),
      .RESVAL  (3'h0)
  ) u_ctrl_pattern (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ctrl_pattern_we),
      .wd(ctrl_pattern_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ctrl.pattern.q),

      // to register interface (read)
      .qs(ctrl_pattern_qs)
  );


  // R[color]: V(False)

  prim_subreg #(
      .DW      (24),
      .SWACCESS("RW"),
      .RESVAL  (24'h0)
  ) u_color (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(color_we),
      .wd(color_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.color.q),

      // to register interface (read)
      .qs(color_qs)
  );


  // R[status]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.status.de),
      .d (hw2reg.status.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(status_qs)
  );


  // R[frame_cnt]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_frame_cnt (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.frame_cnt.de),
      .d (hw2reg.frame_cnt.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(frame_cnt_qs)
  );




  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == HDMI_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == HDMI_COLOR_OFFSET);
    addr_hit[2] = (reg_addr == HDMI_STATUS_OFFSET);
    addr_hit[3] = (reg_addr == HDMI_FRAME_CNT_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(HDMI_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(HDMI_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(HDMI_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(HDMI_PERMIT[3] & ~reg_be)))));
  end

  assign ctrl_en_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_en_wd = reg_wdata[0];

  assign ctrl_pattern_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_pattern_wd = reg_wdata[3:1];

  assign color_we = addr_hit[1] & reg_we & !reg_error;
  assign color_wd = reg_wdata[23:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0]   = ctrl_en_qs;
        reg_rdata_next[3:1] = ctrl_pattern_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[23:0] = color_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = status_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = frame_cnt_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module hdmi_reg_top_intf #(
    parameter  int AW = 5,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    REG_BUS.out regbus_win_mst[1-1:0],
    // To HW
    output hdmi_reg_pkg::hdmi_reg2hw_t reg2hw,  // Write
    input hdmi_reg_pkg::hdmi_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  reg_bus_req_t s_reg_win_req[1-1:0];
  reg_bus_rsp_t s_reg_win_rsp[1-1:0];
  for (genvar i = 0; i < 1; i++) begin : gen_assign_window_structs
    `REG_BUS_ASSIGN_TO_REQ(s_reg_win_req[i], regbus_win_mst[i])
    `REG_BUS_ASSIGN_FROM_RSP(regbus_win_mst[i], s_reg_win_rsp[i])
  end



  hdmi_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg_req_win_o(s_reg_win_req),
      .reg_rsp_win_i(s_reg_win_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


