// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package hdmi_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} en;
    struct packed {logic [2:0] q;} pattern;
  } hdmi_reg2hw_ctrl_reg_t;

  typedef struct packed {logic [23:0] q;} hdmi_reg2hw_color_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } hdmi_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } hdmi_hw2reg_frame_cnt_reg_t;

  // Register -> HW type
  typedef struct packed {
    hdmi_reg2hw_ctrl_reg_t  ctrl;   // [27:24]
    hdmi_reg2hw_color_reg_t color;  // [23:0]
  } hdmi_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    hdmi_hw2reg_status_reg_t status;  // [34:33]
    hdmi_hw2reg_frame_cnt_reg_t frame_cnt;  // [32:0]
  } hdmi_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] HDMI_CTRL_OFFSET = 5'h0;
  parameter logic [BlockAw-1:0] HDMI_COLOR_OFFSET = 5'h4;
  parameter logic [BlockAw-1:0] HDMI_STATUS_OFFSET = 5'h8;
  parameter logic [BlockAw-1:0] HDMI_FRAME_CNT_OFFSET = 5'hc;

  // Window parameters
  parameter logic [BlockAw-1:0] HDMI_PIXEL_OFFSET = 5'h10;
  parameter int unsigned HDMI_PIXEL_SIZE = 'h4;

  // Register index
  typedef enum int {
    HDMI_CTRL,
    HDMI_COLOR,
    HDMI_STATUS,
    HDMI_FRAME_CNT
  } hdmi_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] HDMI_PERMIT[4] = '{
      4'b0001,  // index[0] HDMI_CTRL
      4'b0111,  // index[1] HDMI_COLOR
      4'b0001,  // index[2] HDMI_STATUS
      4'b1111  // index[3] HDMI_FRAME_CNT
  };

endpackage

