// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package serial_link_xheep_wrapper_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic q;} serial_link_xheep_wrapper_reg2hw_rx_mode_reg_t;

  // Register -> HW type
  typedef struct packed {
    serial_link_xheep_wrapper_reg2hw_rx_mode_reg_t rx_mode;  // [0:0]
  } serial_link_xheep_wrapper_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SERIAL_LINK_XHEEP_WRAPPER_RX_MODE_OFFSET = 2'h0;

  // Register index
  typedef enum int {SERIAL_LINK_XHEEP_WRAPPER_RX_MODE} serial_link_xheep_wrapper_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SERIAL_LINK_XHEEP_WRAPPER_PERMIT[1] = '{
      4'b0001  // index[0] SERIAL_LINK_XHEEP_WRAPPER_RX_MODE
  };

endpackage

