// Copyright EPFL contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// CTRL register file of the Bambu HLS 'dot_product' core, built on regtool.
//
// Bambu cannot generate an 's_axilite' control port (its cores only expose
// clock/reset/start_port/done_port plus one plain port per C argument), so
// this block plays the role of Vitis HLS' generated dot_product_CTRL_s_axi.v:
// same register map and bit semantics, which is what lets X-HEEP software and
// the shared OBI wrapper stay identical between the two flows. See
// ../data/dot_product_ctrl.hjson for the register map.
//
// Structure (same as the other regtool-based X-HEEP peripherals):
//
//   AXI4-Lite --> axi_lite_to_reg --> dot_product_ctrl_reg_top (generated by
//                                     regtool from the .hjson) <--> this file
//                                     (reg2hw / hw2reg) <--> Bambu core
//
// This file only holds what regtool cannot generate: the handshake with the
// core (a one-cycle start pulse, only while the core is idle), and turning the
// core's done/result strobes into register updates.
//
// a/b/size drive plain input ports of the core and must be held stable while
// it runs (Bambu's 'none' interface samples them on demand), which they are:
// only software writes them.

`include "axi/typedef.svh"
`include "register_interface/typedef.svh"

module dot_product_ctrl_regs #(
    parameter type axi_req_t = logic,
    parameter type axi_rsp_t = logic
) (
    input logic clk_i,
    input logic rst_ni,

    // verilator lint_off UNUSEDSIGNAL
    // (the AXI4-Lite subset is used: id/len/size/burst/... are ignored)
    input  axi_req_t axi_req_i,
    // verilator lint_on UNUSEDSIGNAL
    output axi_rsp_t axi_rsp_o,

    // Bambu core side
    output logic        start_o,      // one-cycle start pulse
    input  logic        done_i,       // one-cycle done pulse
    output logic [31:0] a_o,
    output logic [31:0] b_o,
    output logic [31:0] size_o,
    input  logic [63:0] result_i,
    input  logic        result_vld_i,

    // Vitis-compatible interrupt: GIER.GIE & |ISR
    output logic interrupt_o
);

  import dot_product_ctrl_reg_pkg::*;

  // ---------------------------------------------------------------------
  // AXI4-Lite (the wrapper's AXI struct, reduced to its AXI4-Lite subset)
  // to register interface
  // ---------------------------------------------------------------------
  typedef logic [31:0] addr_t;
  typedef logic [31:0] data_t;
  typedef logic [3:0] strb_t;

  `AXI_LITE_TYPEDEF_ALL_CT(axil, axil_req_t, axil_rsp_t, addr_t, data_t, strb_t)
  `REG_BUS_TYPEDEF_ALL(reg, addr_t, data_t, strb_t)

  axil_req_t axil_req;
  axil_rsp_t axil_rsp;
  reg_req_t  reg_req;
  reg_rsp_t  reg_rsp;

  always_comb begin
    axil_req = '0;
    axil_req.aw.addr = axi_req_i.aw.addr;
    axil_req.aw.prot = axi_req_i.aw.prot;
    axil_req.aw_valid = axi_req_i.aw_valid;
    axil_req.w.data = axi_req_i.w.data;
    axil_req.w.strb = axi_req_i.w.strb;
    axil_req.w_valid = axi_req_i.w_valid;
    axil_req.b_ready = axi_req_i.b_ready;
    axil_req.ar.addr = axi_req_i.ar.addr;
    axil_req.ar.prot = axi_req_i.ar.prot;
    axil_req.ar_valid = axi_req_i.ar_valid;
    axil_req.r_ready = axi_req_i.r_ready;
  end

  always_comb begin
    axi_rsp_o = '0;
    axi_rsp_o.aw_ready = axil_rsp.aw_ready;
    axi_rsp_o.w_ready = axil_rsp.w_ready;
    axi_rsp_o.b_valid = axil_rsp.b_valid;
    axi_rsp_o.b.resp = axil_rsp.b.resp;
    axi_rsp_o.ar_ready = axil_rsp.ar_ready;
    axi_rsp_o.r_valid = axil_rsp.r_valid;
    axi_rsp_o.r.data = axil_rsp.r.data;
    axi_rsp_o.r.resp = axil_rsp.r.resp;
    axi_rsp_o.r.last = 1'b1;
  end

  axi_lite_to_reg #(
      .ADDR_WIDTH    (32),
      .DATA_WIDTH    (32),
      .axi_lite_req_t(axil_req_t),
      .axi_lite_rsp_t(axil_rsp_t),
      .reg_req_t     (reg_req_t),
      .reg_rsp_t     (reg_rsp_t)
  ) axi_to_reg_i (
      .clk_i         (clk_i),
      .rst_ni        (rst_ni),
      .axi_lite_req_i(axil_req),
      .axi_lite_rsp_o(axil_rsp),
      .reg_req_o     (reg_req),
      .reg_rsp_i     (reg_rsp)
  );

  // ---------------------------------------------------------------------
  // Register file (generated by regtool)
  // ---------------------------------------------------------------------
  // verilator lint_off UNUSEDSIGNAL
  // (the upper halves of the 64-bit pointers, A_HI/B_HI, are kept in the
  // register map for Vitis compatibility but are not used)
  dot_product_ctrl_reg2hw_t reg2hw;
  // verilator lint_on UNUSEDSIGNAL
  dot_product_ctrl_hw2reg_t hw2reg;

  dot_product_ctrl_reg_top #(
      .reg_req_t(reg_req_t),
      .reg_rsp_t(reg_rsp_t)
  ) reg_top_i (
      .clk_i    (clk_i),
      .rst_ni   (rst_ni),
      .reg_req_i(reg_req),
      .reg_rsp_o(reg_rsp),
      .reg2hw   (reg2hw),
      .hw2reg   (hw2reg),
      .devmode_i(1'b1)
  );

  // ---------------------------------------------------------------------
  // Core handshake
  // ---------------------------------------------------------------------
  // The core only ever sees a single-cycle start pulse, and only while it is
  // idle. AP_START is cleared as soon as the pulse is issued (Vitis: clear on
  // handshake); if AUTO_RESTART is set, it is set again when the core is done.
  logic busy_q, busy_d;
  logic start_fire;
  logic done_evt;
  logic restart_evt;
  logic ap_start_d;
  logic ap_idle_d;

  assign start_fire = reg2hw.ap_ctrl.ap_start.q & ~busy_q;
  assign done_evt = done_i & busy_q;
  assign restart_evt = done_evt & reg2hw.ap_ctrl.auto_restart.q;

  assign start_o = start_fire;

  // Next state of the core's busy flag and of AP_START. AP_IDLE is written
  // from these, so that it changes on the same clock edge as AP_DONE.
  assign busy_d = start_fire | (busy_q & ~done_evt);
  assign ap_start_d = restart_evt | (reg2hw.ap_ctrl.ap_start.q & ~start_fire);
  assign ap_idle_d = ~busy_d & ~ap_start_d;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      busy_q <= 1'b0;
    end else begin
      busy_q <= busy_d;
    end
  end

  // ---------------------------------------------------------------------
  // Hardware sets that must not be lost
  // ---------------------------------------------------------------------
  // When software clears a bit (clear-on-read, or write-1-to-clear) in the very
  // same clock cycle in which hardware sets it, software wins and the hardware
  // set is lost (prim_subreg_arb.sv). The core pulses done/result-valid only
  // once, so losing that set would leave the caller polling AP_DONE forever
  // (this actually happened: a poll of AP_CTRL landed in the cycle of the done
  // pulse). Every set is therefore repeated until the bit is seen set: the
  // register file shows the bit one cycle after the set that took effect, and
  // that is when the retry stops, so a set can be repeated but never doubled.
  logic ap_done_set, ap_ready_set, result_set, isr_done_set, isr_ready_set;
  logic ap_done_pend_q, ap_ready_pend_q, result_pend_q, isr_done_pend_q, isr_ready_pend_q;

  assign ap_done_set = done_evt | ap_done_pend_q;
  assign ap_ready_set = done_evt | ap_ready_pend_q;
  assign result_set = result_vld_i | result_pend_q;
  assign isr_done_set = (reg2hw.ier.ap_done.q & done_evt) | isr_done_pend_q;
  assign isr_ready_set = (reg2hw.ier.ap_ready.q & done_evt) | isr_ready_pend_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      ap_done_pend_q <= 1'b0;
      ap_ready_pend_q <= 1'b0;
      result_pend_q <= 1'b0;
      isr_done_pend_q <= 1'b0;
      isr_ready_pend_q <= 1'b0;
    end else begin
      ap_done_pend_q <= ap_done_set & ~reg2hw.ap_ctrl.ap_done.q;
      ap_ready_pend_q <= ap_ready_set & ~reg2hw.ap_ctrl.ap_ready.q;
      result_pend_q <= result_set & ~reg2hw.result_ctrl.q;
      isr_done_pend_q <= isr_done_set & ~reg2hw.isr.ap_done.q;
      isr_ready_pend_q <= isr_ready_set & ~reg2hw.isr.ap_ready.q;
    end
  end

  assign a_o = reg2hw.a_lo.q;
  assign b_o = reg2hw.b_lo.q;
  assign size_o = reg2hw.size.q;

  // ---------------------------------------------------------------------
  // hw2reg: what the hardware writes into the registers
  // ---------------------------------------------------------------------
  always_comb begin
    hw2reg = '0;

    // ap_start: cleared when the core accepts it, set again by auto-restart
    if (start_fire) begin
      hw2reg.ap_ctrl.ap_start.d  = 1'b0;
      hw2reg.ap_ctrl.ap_start.de = 1'b1;
    end else if (restart_evt) begin
      hw2reg.ap_ctrl.ap_start.d  = 1'b1;
      hw2reg.ap_ctrl.ap_start.de = 1'b1;
    end

    // ap_done / ap_ready: set when the core is done (cleared on read)
    hw2reg.ap_ctrl.ap_done.d = 1'b1;
    hw2reg.ap_ctrl.ap_done.de = ap_done_set;
    hw2reg.ap_ctrl.ap_ready.d = 1'b1;
    hw2reg.ap_ctrl.ap_ready.de = ap_ready_set;

    // ap_idle: follows the state of the core (written from its next state)
    hw2reg.ap_ctrl.ap_idle.d = ap_idle_d;
    hw2reg.ap_ctrl.ap_idle.de = 1'b1;

    // result and its valid bit: captured when the core writes them
    hw2reg.result_lo.d = result_i[31:0];
    hw2reg.result_lo.de = result_vld_i;
    hw2reg.result_hi.d = result_i[63:32];
    hw2reg.result_hi.de = result_vld_i;
    hw2reg.result_ctrl.d = 1'b1;
    hw2reg.result_ctrl.de = result_set;

    // interrupt status: set on done/ready if enabled (cleared by software)
    hw2reg.isr.ap_done.d = 1'b1;
    hw2reg.isr.ap_done.de = isr_done_set;
    hw2reg.isr.ap_ready.d = 1'b1;
    hw2reg.isr.ap_ready.de = isr_ready_set;
  end

  assign interrupt_o = reg2hw.gier.q & (reg2hw.isr.ap_done.q | reg2hw.isr.ap_ready.q);

endmodule : dot_product_ctrl_regs
