// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package i2s_tx_sink_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} i2s_tx_sink_reg2hw_control_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } i2s_tx_sink_reg2hw_rxdata_reg_t;

  typedef struct packed {logic [31:0] d;} i2s_tx_sink_hw2reg_rxdata_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } empty;
    struct packed {
      logic d;
      logic de;
    } available;
    struct packed {
      logic d;
      logic de;
    } overflow;
  } i2s_tx_sink_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    i2s_tx_sink_reg2hw_control_reg_t control;  // [64:33]
    i2s_tx_sink_reg2hw_rxdata_reg_t  rxdata;   // [32:0]
  } i2s_tx_sink_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    i2s_tx_sink_hw2reg_rxdata_reg_t rxdata;  // [37:6]
    i2s_tx_sink_hw2reg_status_reg_t status;  // [5:0]
  } i2s_tx_sink_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] I2S_TX_SINK_CONTROL_OFFSET = 4'h0;
  parameter logic [BlockAw-1:0] I2S_TX_SINK_RXDATA_OFFSET = 4'h4;
  parameter logic [BlockAw-1:0] I2S_TX_SINK_STATUS_OFFSET = 4'h8;

  // Reset values for hwext registers and their fields
  parameter logic [31:0] I2S_TX_SINK_RXDATA_RESVAL = 32'h0;

  // Register index
  typedef enum int {
    I2S_TX_SINK_CONTROL,
    I2S_TX_SINK_RXDATA,
    I2S_TX_SINK_STATUS
  } i2s_tx_sink_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] I2S_TX_SINK_PERMIT[3] = '{
      4'b1111,  // index[0] I2S_TX_SINK_CONTROL
      4'b1111,  // index[1] I2S_TX_SINK_RXDATA
      4'b0001  // index[2] I2S_TX_SINK_STATUS
  };

endpackage

