# Authors: Luigi Giuffrida, Michele Caon

FROM condaforge/miniforge3:latest AS conda-source

FROM debian:12-slim

# Set the build-time shell to bash
SHELL ["/bin/bash", "-c"]

# Set ARGs and ENVs
ARG riscv=/tools/riscv
ARG toolchain_path=toolchain.tar.gz
ARG verilator_version=v5.040
ARG verible_version=v0.0-4023-gc1271a00
ENV RISCV_XHEEP=${riscv}
ENV VERILATOR_VERSION=${verilator_version}
ENV VERIBLE_VERSION=${verible_version}
ENV DEBIAN_FRONTEND=noninteractive
ENV TOOLCHAIN_PATH=${toolchain_path}

# Update PATH to include installed tools
# NOTE: use a dedicated variable here and append it to path in env.sh to prevent
#       conda from overriding the PATH at runtime
ENV TOOL_PATH=/tools/verible/verible-${VERIBLE_VERSION}/bin:/tools/verilator/${VERILATOR_VERSION}/bin:${RISCV_XHEEP}/bin

# Install build dependencies, build tools, then remove build-only dependencies
# to keep the final image smaller
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update && apt-get install -y --no-install-recommends \
        # Runtime dependencies
        lcov libelf1 libelf-dev libftdi1-2 libssl-dev libglib2.0-dev libudev-dev libusb-1.0-0 \
        lsb-release texinfo bc zlib1g-dev picocom python3-venv python3-dev git \
        wget python3 make coreutils libfindbin-libs-perl g++ curl

# Install X-HEEP GCC/LLVM RISC-V toolchain
RUN --mount=type=bind,source=${TOOLCHAIN_PATH},target=${TOOLCHAIN_PATH} \
    mkdir -p ${RISCV_XHEEP} && \
    tar -xz -o -C ${RISCV_XHEEP} --strip-components=1 -f ${TOOLCHAIN_PATH}

# Install CORE-V GCC RISC-V toolchain
RUN mkdir -p ${RISCV_XHEEP} && \
    wget -qO- https://github.com/x-heep/corev-gcc/releases/download/cv32e40pv2-release/corev-openhw-gcc-ubuntu2204-20240530.tar.gz | tar -xz -o -C ${RISCV_XHEEP} --strip-components=1

# Install Verilator
RUN --mount=type=tmpfs,destination=/tmp/verilator \
    --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update && apt-get install -y --no-install-recommends \
        # Build-time dependencies for tools
        autoconf autotools-dev build-essential libmpc-dev libmpfr-dev libgmp-dev gperf libtool patchutils \
        cmake flex bison libexpat-dev gawk ninja-build help2man libfl-dev && \
    git clone https://github.com/verilator/verilator.git /tmp/verilator && \
    cd /tmp/verilator && git checkout ${VERILATOR_VERSION} && \
    autoconf && ./configure --prefix=/tools/verilator/${VERILATOR_VERSION} && \
    make -j$(nproc) && make install && \
    apt-get purge --auto-remove -y \
        # Clean up build-time dependencies
        autoconf autotools-dev build-essential libfl-dev

# Install Verible
RUN mkdir -p /tools/verible && \
    wget -qO- https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-x86_64.tar.gz | \
    tar -xz -o -C /tools/verible

# Install conda & setup environment
COPY --from=conda-source /opt/conda /opt/conda
RUN --mount=type=bind,source=util/conda_environment.yml,target=conda_environment.yml \
    --mount=type=bind,source=util/python-requirements.txt,target=python-requirements.txt \
    --mount=type=bind,source=docs/python-requirements.txt,target=docs/python-requirements.txt \
    /opt/conda/bin/conda config --set auto_activate_base false && \
    /opt/conda/bin/conda config --add channels conda-forge && \
    /opt/conda/bin/conda config --set channel_priority strict && \
    /opt/conda/bin/conda env create -f conda_environment.yml && \
    /opt/conda/bin/conda clean -afy && \
    /opt/conda/bin/conda init --system

# Copy profile scripts (conda initialization and welcome message)
COPY util/docker/env.sh util/docker/motd.sh /etc/profile.d/
RUN chmod +x /etc/profile.d/env.sh /etc/profile.d/motd.sh
RUN echo "source /etc/profile.d/env.sh" >> /etc/bash.bashrc

# Mark X-HEEP repo as a safe so new version of git don't complain when running util/git-diff.py
RUN git config --global --add safe.directory '*'
WORKDIR /workspace/x-heep

# Copy and set up the entrypoint script
COPY util/docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Default command to run when no other command is specified
CMD ["/bin/bash", "-l"]
