#!/usr/bin/env bash
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Runs Bambu HLS for the dot_product engine, copies the generated RTL into
# rtl/hls/, and (re)generates dot_product_bambu.core listing it -- so
# `make verilator-build` / `make vivado-fpga` can pick it up via FuseSoC when
# built with `--flag use_hls_example --flag use_bambu_hls`.
#
# Usage:
#   ./generate_core.sh
#
# Bambu runs in Docker by default (the only host dependency; the image is
# built on first use), or from a native install with BAMBU=/path/to/bambu.
# See ../bambu.sh.
#
# Skips re-running Bambu if rtl/hls/ already holds RTL newer than every input
# that could affect it. Pass FORCE=1 to regenerate unconditionally.
#
# ./generate_core.sh clean
#   Removes the generated artifacts: the Bambu work directory and rtl/hls/.
#   Does NOT remove dot_product_bambu.core -- that file is committed to git
#   (unlike rtl/hls/ and dot_product_proj/, which are gitignored) because
#   FuseSoC needs it to resolve epfl:ip:dot_product_bambu as a dependency
#   *before* it runs any pre_build hook -- if it didn't exist at all,
#   dependency resolution would fail outright and the hook that (re)generates
#   rtl/hls/ would never run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SELF="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
cd "$SCRIPT_DIR"

WORK_DIR="dot_product_proj"
DST_DIR="rtl/hls"
CORE_FILE="dot_product_bambu.core"

if [ "${1:-}" = "clean" ]; then
  rm -rf "$WORK_DIR" "$DST_DIR"
  echo "Removed $WORK_DIR/ and $DST_DIR/."
  echo "$CORE_FILE was left untouched (it's committed to git, not generated)."
  exit 0
fi

# Everything the generated RTL depends on: the kernel, the shared header, the
# Bambu flags/script, the runner, and the Docker environment (Bambu version).
INPUTS=(
  dot_product.cpp
  ../../common/dot_product/dot_product.h
  run_bambu.sh
  ../bambu.sh
  ../Dockerfile
  "$SELF"
)

if [ "${FORCE:-0}" != "1" ] && [ -f "$CORE_FILE" ] && [ -d "$DST_DIR" ] \
  && [ -n "$(find "$DST_DIR" -maxdepth 1 -name '*.v' -print -quit)" ]; then
  stale_src=$(find "${INPUTS[@]}" -newer "$CORE_FILE" 2>/dev/null | head -1)
  if [ -z "$stale_src" ]; then
    echo "dot_product RTL in $DST_DIR/ is already up to date (nothing changed since last generation) -- skipping Bambu."
    echo "Set FORCE=1 to regenerate anyway."
    exit 0
  fi
fi

rm -rf "$WORK_DIR"
./run_bambu.sh synth

mkdir -p "$DST_DIR"
rm -f "$DST_DIR"/*.v
# Bambu writes the whole design (top + every library component it uses) into
# a single self-contained <top>.v.
cp "$WORK_DIR"/*.v "$DST_DIR"/

# Strip the per-component `timescale directive Bambu emits: no other file in
# this project sets one (X-HEEP relies on Verilator's single implicit
# timescale), so leaving it in would make every other module in the whole
# design "inconsistent" in Verilator 5's eyes (TIMESCALEMOD warning) rather
# than just this file.
sed -i '/^`timescale /d' "$DST_DIR"/*.v

HLS_FILES=$(cd "$DST_DIR" && ls ./*.v | sed 's#^\./##' | sort | sed 's/^/    - rtl\/hls\//')

cat >"$CORE_FILE" <<EOF
CAPI=2:

# Auto-generated by generate_core.sh -- do not edit by hand.
# Regenerate with:
#   ./generate_core.sh
# (Bambu runs in Docker by default; see ../bambu.sh.)

name: "epfl:ip:dot_product_bambu"
description: "Bambu HLS-generated streaming dot-product core with its X-HEEP adapter (AXI struct mapping + CTRL register file)."

filesets:
  files_rtl:
    depend:
    - x-heep:ip:dot_product_bambu_ctrl
    files:
$HLS_FILES
    - rtl/dot_product_hls_adapter.sv
    file_type: systemVerilogSource

  verilator-waiver:
    files:
    - dot_product.vlt
    file_type: vlt

targets:
  default:
    filesets:
    - files_rtl
    - tool_verilator ? (verilator-waiver)
EOF

n_files=$(echo "$HLS_FILES" | wc -l)
echo "Generated $CORE_FILE: ${n_files} Bambu RTL file(s) + adapter, from $WORK_DIR/."
