#!/usr/bin/env python3
# Copyright 2026 Politecnico di Torino
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# This script generates a thin synthesis-only wrapper, `x_heep_system_synth_top`,
# that:
#   - has the EXACT same parameter list and port list as `x_heep_system`,
#     MINUS the 6 xif interface ports (extracted verbatim by text
#     processing, so it always matches whatever `mcu-gen` produced - no
#     manual upkeep);
#   - instantiates `x_heep_system`, binding the 6 xif ports to internal
#     `if_xif` instances (tied off / unused - fine, no CPU extension is
#     enabled in the ASIC synthesis flows) and forwarding every other port 1:1.
#
# The synthesized netlist keeps `x_heep_system_synth_top` as its top module;
# the post-synthesis simulation wraps it in a shim with x_heep_system's
# interface (see scripts/sim/modelsim/generate_postsyn_sim_shim.py).


import re
import sys
from pathlib import Path

SRC = Path("../../../hw/system/x_heep_system.sv")
OUT = Path("x_heep_system_synth_top.sv")

XIF_PORTS = [
    ("xif_compressed_if", "cpu_compressed"),
    ("xif_issue_if", "cpu_issue"),
    ("xif_commit_if", "cpu_commit"),
    ("xif_mem_if", "cpu_mem"),
    ("xif_mem_result_if", "cpu_mem_result"),
    ("xif_result_if", "cpu_result"),
]


def extract_header(text: str) -> str:
    """Return the full `module x_heep_system #( ... ) ( ... );` header
    (parameter list + port list), by tracking paren depth from the module
    keyword to the terminating top-level ';'."""
    m = re.search(r"\bmodule\s+x_heep_system\b", text)
    if m is None:
        sys.exit(f"ERROR: 'module x_heep_system' not found in {SRC}")
    start = m.start()
    depth = 0
    seen_paren = False
    i = m.end()
    while i < len(text):
        c = text[i]
        if c == "(":
            depth += 1
            seen_paren = True
        elif c == ")":
            depth -= 1
        elif c == ";" and seen_paren and depth == 0:
            return text[start : i + 1]
        i += 1
    sys.exit(f"ERROR: could not find end of 'module x_heep_system' header in {SRC}")


def strip_xif_ports(header: str) -> str:
    """Drop the 6 `if_xif.<modport> xif_*_if,` port declaration lines."""
    out_lines = []
    for line in header.splitlines():
        if re.search(r"\bif_xif\s*\.\s*cpu_\w+\s+xif_\w+_if\b", line):
            continue
        out_lines.append(line)
    # Clean up a possible dangling trailing comma left on the last real port
    # (the removed lines were originally followed by more ports+ ')').
    text = "\n".join(out_lines)
    text = re.sub(r",(\s*)\)\s*;\s*$", r"\1);", text)
    return text


def main():
    if not SRC.exists():
        sys.exit(
            f"ERROR: {SRC} not found. Run 'make mcu-gen' before the ASIC synthesis flows."
        )
    src_text = SRC.read_text()

    header = extract_header(src_text)
    wrapper_header = strip_xif_ports(header).replace(
        "module x_heep_system", "module x_heep_system_synth_top", 1
    )

    xif_decls = "\n".join(f"  if_xif {sig}_i();" for sig, _modport in XIF_PORTS)
    xif_conns = [f".{sig}({sig}_i)" for sig, _modport in XIF_PORTS]
    conns = [".*"] + xif_conns
    mode = "same port types, connected with .*"
    conns_text = ",\n".join(f"      {c}" for c in conns)

    wrapper = f"""\
// Auto-generated by scripts/synthesis/generate_synth_top.py
// from {SRC} - do not edit by hand, re-run the generator instead.
//
// Synthesis-only top: same parameter/port list as `x_heep_system` minus its
// 6 unconnected `if_xif` interface ports (tied off here to internal, unused
// interface instances, since no CPU extension is enabled in this flow).
// Ports: {mode}.

{wrapper_header}

{xif_decls}

  x_heep_system x_heep_system_i (
{conns_text}
  );

endmodule
"""
    OUT.write_text(wrapper)
    print(f"[generate_synth_top] Wrote {OUT} (top: x_heep_system_synth_top; {mode})")


if __name__ == "__main__":
    main()
