// Synthesis wrapper for core_v_mini_mcu.
// Instantiates if_xif internally and ties off all XIF ports (no coprocessor).
// Use this module as top-level for Yosys synthesis instead of core_v_mini_mcu.

module core_v_mini_mcu_synth_wrap
  import obi_pkg::*;
  import reg_pkg::*;
  import fifo_pkg::*;
#(
    parameter EXT_XBAR_NMASTER = 0,
    parameter AO_SPC_NUM       = 0,
    parameter EXT_HARTS        = 0,
    parameter AO_SPC_NUM_RND      = AO_SPC_NUM == 0 ? 0 : AO_SPC_NUM - 1,
    parameter EXT_XBAR_NMASTER_RND = EXT_XBAR_NMASTER == 0 ? 1 : EXT_XBAR_NMASTER,
    parameter EXT_DOMAINS_RND     = core_v_mini_mcu_pkg::EXTERNAL_DOMAINS == 0 ? 1 : core_v_mini_mcu_pkg::EXTERNAL_DOMAINS,
    parameter NEXT_INT_RND        = core_v_mini_mcu_pkg::NEXT_INT == 0 ? 1 : core_v_mini_mcu_pkg::NEXT_INT,
    parameter EXT_HARTS_RND       = EXT_HARTS == 0 ? 1 : EXT_HARTS
) (
    // same port list as core_v_mini_mcu, minus the XIF interface ports
    input  logic rst_ni,
    input  logic clk_i,
    input  logic boot_select_i,
    input  logic execute_from_flash_i,
    input  logic jtag_tck_i,
    input  logic jtag_tms_i,
    input  logic jtag_trst_ni,
    input  logic jtag_tdi_i,
    output logic jtag_tdo_o,
    input  logic uart_rx_i,
    output logic uart_tx_o,
    output logic exit_valid_o,
    input  logic gpio_0_i,  output logic gpio_0_o,  output logic gpio_0_oe_o,
    input  logic gpio_1_i,  output logic gpio_1_o,  output logic gpio_1_oe_o,
    input  logic gpio_2_i,  output logic gpio_2_o,  output logic gpio_2_oe_o,
    input  logic gpio_3_i,  output logic gpio_3_o,  output logic gpio_3_oe_o,
    input  logic gpio_4_i,  output logic gpio_4_o,  output logic gpio_4_oe_o,
    input  logic gpio_5_i,  output logic gpio_5_o,  output logic gpio_5_oe_o,
    input  logic gpio_6_i,  output logic gpio_6_o,  output logic gpio_6_oe_o,
    input  logic gpio_7_i,  output logic gpio_7_o,  output logic gpio_7_oe_o,
    input  logic gpio_8_i,  output logic gpio_8_o,  output logic gpio_8_oe_o,
    input  logic gpio_9_i,  output logic gpio_9_o,  output logic gpio_9_oe_o,
    input  logic gpio_10_i, output logic gpio_10_o, output logic gpio_10_oe_o,
    input  logic gpio_11_i, output logic gpio_11_o, output logic gpio_11_oe_o,
    input  logic gpio_12_i, output logic gpio_12_o, output logic gpio_12_oe_o,
    input  logic gpio_13_i, output logic gpio_13_o, output logic gpio_13_oe_o,
    input  logic spi_flash_sck_i,  output logic spi_flash_sck_o,  output logic spi_flash_sck_oe_o,
    input  logic spi_flash_cs_0_i, output logic spi_flash_cs_0_o, output logic spi_flash_cs_0_oe_o,
    input  logic spi_flash_cs_1_i, output logic spi_flash_cs_1_o, output logic spi_flash_cs_1_oe_o,
    input  logic spi_flash_sd_0_i, output logic spi_flash_sd_0_o, output logic spi_flash_sd_0_oe_o,
    input  logic spi_flash_sd_1_i, output logic spi_flash_sd_1_o, output logic spi_flash_sd_1_oe_o,
    input  logic spi_flash_sd_2_i, output logic spi_flash_sd_2_o, output logic spi_flash_sd_2_oe_o,
    input  logic spi_flash_sd_3_i, output logic spi_flash_sd_3_o, output logic spi_flash_sd_3_oe_o,
    input  logic spi_sck_i,   output logic spi_sck_o,   output logic spi_sck_oe_o,
    input  logic spi_cs_0_i,  output logic spi_cs_0_o,  output logic spi_cs_0_oe_o,
    input  logic spi_cs_1_i,  output logic spi_cs_1_o,  output logic spi_cs_1_oe_o,
    input  logic spi_sd_0_i,  output logic spi_sd_0_o,  output logic spi_sd_0_oe_o,
    input  logic spi_sd_1_i,  output logic spi_sd_1_o,  output logic spi_sd_1_oe_o,
    input  logic spi_sd_2_i,  output logic spi_sd_2_o,  output logic spi_sd_2_oe_o,
    input  logic spi_sd_3_i,  output logic spi_sd_3_o,  output logic spi_sd_3_oe_o,
    input  logic spi_slave_sck_i,
    input  logic gpio_14_i, output logic gpio_14_o, output logic gpio_14_oe_o,
    input  logic spi_slave_cs_i,
    input  logic gpio_15_i, output logic gpio_15_o, output logic gpio_15_oe_o,
    input  logic spi_slave_miso_i, output logic spi_slave_miso_o, output logic spi_slave_miso_oe_o,
    input  logic gpio_16_i, output logic gpio_16_o, output logic gpio_16_oe_o,
    input  logic spi_slave_mosi_i,
    input  logic gpio_17_i, output logic gpio_17_o, output logic gpio_17_oe_o,
    input  logic pdm2pcm_pdm_i,  output logic pdm2pcm_pdm_o,  output logic pdm2pcm_pdm_oe_o,
    input  logic gpio_18_i, output logic gpio_18_o, output logic gpio_18_oe_o,
    input  logic pdm2pcm_clk_i,  output logic pdm2pcm_clk_o,  output logic pdm2pcm_clk_oe_o,
    input  logic gpio_19_i, output logic gpio_19_o, output logic gpio_19_oe_o,
    input  logic i2s_sck_i, output logic i2s_sck_o, output logic i2s_sck_oe_o,
    input  logic gpio_20_i, output logic gpio_20_o, output logic gpio_20_oe_o,
    input  logic i2s_ws_i,  output logic i2s_ws_o,  output logic i2s_ws_oe_o,
    input  logic gpio_21_i, output logic gpio_21_o, output logic gpio_21_oe_o,
    input  logic i2s_sd_i,  output logic i2s_sd_o,  output logic i2s_sd_oe_o,
    input  logic gpio_22_i, output logic gpio_22_o, output logic gpio_22_oe_o,
    input  logic spi2_cs_0_i, output logic spi2_cs_0_o, output logic spi2_cs_0_oe_o,
    input  logic gpio_23_i,   output logic gpio_23_o,   output logic gpio_23_oe_o,
    input  logic spi2_cs_1_i, output logic spi2_cs_1_o, output logic spi2_cs_1_oe_o,
    input  logic gpio_24_i,   output logic gpio_24_o,   output logic gpio_24_oe_o,
    input  logic spi2_sck_i,  output logic spi2_sck_o,  output logic spi2_sck_oe_o,
    input  logic gpio_25_i,   output logic gpio_25_o,   output logic gpio_25_oe_o,
    input  logic spi2_sd_0_i, output logic spi2_sd_0_o, output logic spi2_sd_0_oe_o,
    input  logic gpio_26_i,   output logic gpio_26_o,   output logic gpio_26_oe_o,
    input  logic spi2_sd_1_i, output logic spi2_sd_1_o, output logic spi2_sd_1_oe_o,
    input  logic gpio_27_i,   output logic gpio_27_o,   output logic gpio_27_oe_o,
    input  logic spi2_sd_2_i, output logic spi2_sd_2_o, output logic spi2_sd_2_oe_o,
    input  logic gpio_28_i,   output logic gpio_28_o,   output logic gpio_28_oe_o,
    input  logic spi2_sd_3_i, output logic spi2_sd_3_o, output logic spi2_sd_3_oe_o,
    input  logic gpio_29_i,   output logic gpio_29_o,   output logic gpio_29_oe_o,
    input  logic i2c_scl_i,   output logic i2c_scl_o,   output logic i2c_scl_oe_o,
    input  logic gpio_31_i,   output logic gpio_31_o,   output logic gpio_31_oe_o,
    input  logic i2c_sda_i,   output logic i2c_sda_o,   output logic i2c_sda_oe_o,
    input  logic gpio_30_i,   output logic gpio_30_o,   output logic gpio_30_oe_o,
    input  logic [31:0] hart_id_i,
    input  logic [31:0] xheep_instance_id_i,
    output reg_req_t pad_req_o,
    input  reg_rsp_t pad_resp_i,
    input  obi_req_t  [EXT_XBAR_NMASTER_RND-1:0] ext_xbar_master_req_i,
    output obi_resp_t [EXT_XBAR_NMASTER_RND-1:0] ext_xbar_master_resp_o,
    input  reg_req_t  [AO_SPC_NUM_RND:0] ext_ao_peripheral_slave_req_i,
    output reg_rsp_t  [AO_SPC_NUM_RND:0] ext_ao_peripheral_slave_resp_o,
    output obi_req_t  ext_core_instr_req_o,
    input  obi_resp_t ext_core_instr_resp_i,
    output obi_req_t  ext_core_data_req_o,
    input  obi_resp_t ext_core_data_resp_i,
    output obi_req_t  ext_debug_master_req_o,
    input  obi_resp_t ext_debug_master_resp_i,
    output obi_req_t  [core_v_mini_mcu_pkg::DMA_NUM_MASTER_PORTS-1:0] ext_dma_read_req_o,
    input  obi_resp_t [core_v_mini_mcu_pkg::DMA_NUM_MASTER_PORTS-1:0] ext_dma_read_resp_i,
    output obi_req_t  [core_v_mini_mcu_pkg::DMA_NUM_MASTER_PORTS-1:0] ext_dma_write_req_o,
    input  obi_resp_t [core_v_mini_mcu_pkg::DMA_NUM_MASTER_PORTS-1:0] ext_dma_write_resp_i,
    output obi_req_t  [core_v_mini_mcu_pkg::DMA_NUM_MASTER_PORTS-1:0] ext_dma_addr_req_o,
    input  obi_resp_t [core_v_mini_mcu_pkg::DMA_NUM_MASTER_PORTS-1:0] ext_dma_addr_resp_i,
    output fifo_req_t  [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] hw_fifo_req_o,
    input  fifo_resp_t [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] hw_fifo_resp_i,
    input  logic [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] ext_dma_stop_i,
    input  logic [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] hw_fifo_done_i,
    output reg_req_t ext_peripheral_slave_req_o,
    input  reg_rsp_t ext_peripheral_slave_resp_i,
    output logic [EXT_HARTS_RND-1:0] ext_debug_req_o,
    output logic ext_debug_reset_no,
    input  logic [NEXT_INT_RND-1:0] intr_vector_ext_i,
    input  logic intr_ext_peripheral_i,
    output logic cpu_subsystem_powergate_switch_no,
    input  logic cpu_subsystem_powergate_switch_ack_ni,
    output logic peripheral_subsystem_powergate_switch_no,
    input  logic peripheral_subsystem_powergate_switch_ack_ni,
    output logic [EXT_DOMAINS_RND-1:0] external_subsystem_powergate_switch_no,
    input  logic [EXT_DOMAINS_RND-1:0] external_subsystem_powergate_switch_ack_ni,
    output logic [EXT_DOMAINS_RND-1:0] external_subsystem_powergate_iso_no,
    output logic [EXT_DOMAINS_RND-1:0] external_subsystem_rst_no,
    output logic ext_cpu_subsystem_rst_no,
    output logic [EXT_DOMAINS_RND-1:0] external_ram_banks_set_retentive_no,
    output logic [EXT_DOMAINS_RND-1:0] external_subsystem_clkgate_en_no,
    output logic [31:0] exit_value_o,
    input  logic [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] ext_dma_slot_tx_i,
    input  logic [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] ext_dma_slot_rx_i,
    output logic [core_v_mini_mcu_pkg::DMA_CH_NUM-1:0] dma_done_o
);

  // -------------------------------------------------------------------------
  // Internal XIF interface instances (no coprocessor attached — tied off)
  // -------------------------------------------------------------------------
  if_xif #() xif ();

  // Tie off the coprocessor-side inputs (cpu drives outputs, coproc drives inputs)
  // cpu_compressed: cpu outputs compressed_valid, compressed_req
  //                 cpu inputs  compressed_ready, compressed_resp  <- tie off
  assign xif.compressed_ready = '0;
  assign xif.compressed_resp  = '0;

  // cpu_issue: cpu outputs issue_valid, issue_req
  //            cpu inputs  issue_ready, issue_resp  <- tie off
  assign xif.issue_ready = '0;
  assign xif.issue_resp  = '0;

  // cpu_commit: cpu outputs only — nothing to tie off

  // cpu_mem: cpu inputs mem_valid, mem_req
  //          cpu outputs mem_ready, mem_resp  <- driven by cpu
  //          coproc side: tie off mem_valid, mem_req
  assign xif.mem_valid = '0;
  assign xif.mem_req   = '0;

  // cpu_mem_result: cpu outputs only — nothing to tie off

  // cpu_result: cpu inputs result_valid, result
  //             cpu outputs result_ready
  assign xif.result_valid = '0;
  assign xif.result       = '0;

  // -------------------------------------------------------------------------
  // DUT instantiation
  // -------------------------------------------------------------------------
  core_v_mini_mcu #(
      .EXT_XBAR_NMASTER(EXT_XBAR_NMASTER),
      .AO_SPC_NUM      (AO_SPC_NUM),
      .EXT_HARTS       (EXT_HARTS)
  ) u_core_v_mini_mcu (
      .rst_ni,
      .clk_i,
      .boot_select_i,
      .execute_from_flash_i,
      .jtag_tck_i,   .jtag_tms_i,   .jtag_trst_ni, .jtag_tdi_i,   .jtag_tdo_o,
      .uart_rx_i,    .uart_tx_o,
      .exit_valid_o,
      .gpio_0_i,  .gpio_0_o,  .gpio_0_oe_o,
      .gpio_1_i,  .gpio_1_o,  .gpio_1_oe_o,
      .gpio_2_i,  .gpio_2_o,  .gpio_2_oe_o,
      .gpio_3_i,  .gpio_3_o,  .gpio_3_oe_o,
      .gpio_4_i,  .gpio_4_o,  .gpio_4_oe_o,
      .gpio_5_i,  .gpio_5_o,  .gpio_5_oe_o,
      .gpio_6_i,  .gpio_6_o,  .gpio_6_oe_o,
      .gpio_7_i,  .gpio_7_o,  .gpio_7_oe_o,
      .gpio_8_i,  .gpio_8_o,  .gpio_8_oe_o,
      .gpio_9_i,  .gpio_9_o,  .gpio_9_oe_o,
      .gpio_10_i, .gpio_10_o, .gpio_10_oe_o,
      .gpio_11_i, .gpio_11_o, .gpio_11_oe_o,
      .gpio_12_i, .gpio_12_o, .gpio_12_oe_o,
      .gpio_13_i, .gpio_13_o, .gpio_13_oe_o,
      .spi_flash_sck_i,  .spi_flash_sck_o,  .spi_flash_sck_oe_o,
      .spi_flash_cs_0_i, .spi_flash_cs_0_o, .spi_flash_cs_0_oe_o,
      .spi_flash_cs_1_i, .spi_flash_cs_1_o, .spi_flash_cs_1_oe_o,
      .spi_flash_sd_0_i, .spi_flash_sd_0_o, .spi_flash_sd_0_oe_o,
      .spi_flash_sd_1_i, .spi_flash_sd_1_o, .spi_flash_sd_1_oe_o,
      .spi_flash_sd_2_i, .spi_flash_sd_2_o, .spi_flash_sd_2_oe_o,
      .spi_flash_sd_3_i, .spi_flash_sd_3_o, .spi_flash_sd_3_oe_o,
      .spi_sck_i,  .spi_sck_o,  .spi_sck_oe_o,
      .spi_cs_0_i, .spi_cs_0_o, .spi_cs_0_oe_o,
      .spi_cs_1_i, .spi_cs_1_o, .spi_cs_1_oe_o,
      .spi_sd_0_i, .spi_sd_0_o, .spi_sd_0_oe_o,
      .spi_sd_1_i, .spi_sd_1_o, .spi_sd_1_oe_o,
      .spi_sd_2_i, .spi_sd_2_o, .spi_sd_2_oe_o,
      .spi_sd_3_i, .spi_sd_3_o, .spi_sd_3_oe_o,
      .spi_slave_sck_i,
      .gpio_14_i, .gpio_14_o, .gpio_14_oe_o,
      .spi_slave_cs_i,
      .gpio_15_i, .gpio_15_o, .gpio_15_oe_o,
      .spi_slave_miso_i, .spi_slave_miso_o, .spi_slave_miso_oe_o,
      .gpio_16_i, .gpio_16_o, .gpio_16_oe_o,
      .spi_slave_mosi_i,
      .gpio_17_i, .gpio_17_o, .gpio_17_oe_o,
      .pdm2pcm_pdm_i,  .pdm2pcm_pdm_o,  .pdm2pcm_pdm_oe_o,
      .gpio_18_i, .gpio_18_o, .gpio_18_oe_o,
      .pdm2pcm_clk_i,  .pdm2pcm_clk_o,  .pdm2pcm_clk_oe_o,
      .gpio_19_i, .gpio_19_o, .gpio_19_oe_o,
      .i2s_sck_i, .i2s_sck_o, .i2s_sck_oe_o,
      .gpio_20_i, .gpio_20_o, .gpio_20_oe_o,
      .i2s_ws_i,  .i2s_ws_o,  .i2s_ws_oe_o,
      .gpio_21_i, .gpio_21_o, .gpio_21_oe_o,
      .i2s_sd_i,  .i2s_sd_o,  .i2s_sd_oe_o,
      .gpio_22_i, .gpio_22_o, .gpio_22_oe_o,
      .spi2_cs_0_i, .spi2_cs_0_o, .spi2_cs_0_oe_o,
      .gpio_23_i,   .gpio_23_o,   .gpio_23_oe_o,
      .spi2_cs_1_i, .spi2_cs_1_o, .spi2_cs_1_oe_o,
      .gpio_24_i,   .gpio_24_o,   .gpio_24_oe_o,
      .spi2_sck_i,  .spi2_sck_o,  .spi2_sck_oe_o,
      .gpio_25_i,   .gpio_25_o,   .gpio_25_oe_o,
      .spi2_sd_0_i, .spi2_sd_0_o, .spi2_sd_0_oe_o,
      .gpio_26_i,   .gpio_26_o,   .gpio_26_oe_o,
      .spi2_sd_1_i, .spi2_sd_1_o, .spi2_sd_1_oe_o,
      .gpio_27_i,   .gpio_27_o,   .gpio_27_oe_o,
      .spi2_sd_2_i, .spi2_sd_2_o, .spi2_sd_2_oe_o,
      .gpio_28_i,   .gpio_28_o,   .gpio_28_oe_o,
      .spi2_sd_3_i, .spi2_sd_3_o, .spi2_sd_3_oe_o,
      .gpio_29_i,   .gpio_29_o,   .gpio_29_oe_o,
      .i2c_scl_i,   .i2c_scl_o,   .i2c_scl_oe_o,
      .gpio_31_i,   .gpio_31_o,   .gpio_31_oe_o,
      .i2c_sda_i,   .i2c_sda_o,   .i2c_sda_oe_o,
      .gpio_30_i,   .gpio_30_o,   .gpio_30_oe_o,
      .hart_id_i,
      .xheep_instance_id_i,
      .xif_compressed_if (xif.cpu_compressed),
      .xif_issue_if      (xif.cpu_issue),
      .xif_commit_if     (xif.cpu_commit),
      .xif_mem_if        (xif.cpu_mem),
      .xif_mem_result_if (xif.cpu_mem_result),
      .xif_result_if     (xif.cpu_result),
      .pad_req_o,
      .pad_resp_i,
      .ext_xbar_master_req_i,
      .ext_xbar_master_resp_o,
      .ext_ao_peripheral_slave_req_i,
      .ext_ao_peripheral_slave_resp_o,
      .ext_core_instr_req_o,    .ext_core_instr_resp_i,
      .ext_core_data_req_o,     .ext_core_data_resp_i,
      .ext_debug_master_req_o,  .ext_debug_master_resp_i,
      .ext_dma_read_req_o,      .ext_dma_read_resp_i,
      .ext_dma_write_req_o,     .ext_dma_write_resp_i,
      .ext_dma_addr_req_o,      .ext_dma_addr_resp_i,
      .hw_fifo_req_o,           .hw_fifo_resp_i,
      .ext_dma_stop_i,          .hw_fifo_done_i,
      .ext_peripheral_slave_req_o, .ext_peripheral_slave_resp_i,
      .ext_debug_req_o,
      .ext_debug_reset_no,
      .intr_vector_ext_i,
      .intr_ext_peripheral_i,
      .cpu_subsystem_powergate_switch_no,
      .cpu_subsystem_powergate_switch_ack_ni,
      .peripheral_subsystem_powergate_switch_no,
      .peripheral_subsystem_powergate_switch_ack_ni,
      .external_subsystem_powergate_switch_no,
      .external_subsystem_powergate_switch_ack_ni,
      .external_subsystem_powergate_iso_no,
      .external_subsystem_rst_no,
      .ext_cpu_subsystem_rst_no,
      .external_ram_banks_set_retentive_no,
      .external_subsystem_clkgate_en_no,
      .exit_value_o,
      .ext_dma_slot_tx_i,
      .ext_dma_slot_rx_i,
      .dma_done_o
  );

endmodule // core_v_mini_mcu_synth_wrap