#!/usr/bin/env bash
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Runs Dynamatic for the dot_product engine, copies the generated Verilog into
# rtl/hls/, and (re)generates dot_product_dynamatic.core listing it -- so
# `make verilator-build` / `make vivado-fpga` can pick it up via FuseSoC when
# built with `--flag use_hls_example --flag use_dynamatic_hls`.
#
# Usage:
#   ./generate_core.sh
#
# Dynamatic runs in Docker by default (the only host dependency; the image is
# built on first use), or from a native build with
# DYNAMATIC_DIR=/path/to/dynamatic. See ../dynamatic.sh.
#
# Skips re-running Dynamatic if rtl/hls/ already holds RTL newer than every
# input that could affect it. Pass FORCE=1 to regenerate unconditionally.
#
# ./generate_core.sh clean
#   Removes the generated artifacts: the Dynamatic work directory and rtl/hls/.
#   Does NOT remove dot_product_dynamatic.core -- that file is committed to git
#   (unlike rtl/hls/ and dot_product_proj/, which are gitignored) because
#   FuseSoC needs it to resolve epfl:ip:dot_product_dynamatic as a dependency
#   *before* it runs any pre_build hook -- if it didn't exist at all,
#   dependency resolution would fail outright and the hook that (re)generates
#   rtl/hls/ would never run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SELF="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
cd "$SCRIPT_DIR"

WORK_DIR="dot_product_proj"
DST_DIR="rtl/hls"
CORE_FILE="dot_product_dynamatic.core"

if [ "${1:-}" = "clean" ]; then
  rm -rf "$WORK_DIR" "$DST_DIR"
  echo "Removed $WORK_DIR/ and $DST_DIR/."
  echo "$CORE_FILE was left untouched (it's committed to git, not generated)."
  exit 0
fi

# Everything the generated RTL depends on: the kernel, the shared header (and
# testbench, which Dynamatic compiles with the kernel), the Dynamatic
# commands/script, the runner, and the Docker environment (Dynamatic version).
INPUTS=(
  dot_product.c
  ../../common/dot_product/dot_product.h
  ../../common/dot_product/dot_product_tb.cpp
  run_dynamatic.sh
  ../dynamatic.sh
  ../Dockerfile
  "$SELF"
)

if [ "${FORCE:-0}" != "1" ] && [ -f "$CORE_FILE" ] && [ -d "$DST_DIR" ] \
  && [ -n "$(find "$DST_DIR" -maxdepth 1 -name '*.v' -print -quit)" ]; then
  stale_src=$(find "${INPUTS[@]}" -newer "$CORE_FILE" 2>/dev/null | head -1)
  if [ -z "$stale_src" ]; then
    echo "dot_product RTL in $DST_DIR/ is already up to date (nothing changed since last generation) -- skipping Dynamatic."
    echo "Set FORCE=1 to regenerate anyway."
    exit 0
  fi
fi

./run_dynamatic.sh synth

mkdir -p "$DST_DIR"
rm -f "$DST_DIR"/*.v
# Dynamatic writes one file per component of the circuit (its RTL library,
# specialised per width), plus dot_product.v (the circuit) and
# dot_product_wrapper.v (the top level, with BRAM-style memory ports).
cp "$WORK_DIR"/out/hdl/*.v "$DST_DIR"/

# Strip the `timescale directive Dynamatic emits in every file: no other file
# in this project sets one (X-HEEP relies on Verilator's single implicit
# timescale), so leaving it in would make every other module in the whole
# design "inconsistent" in Verilator 5's eyes (TIMESCALEMOD warning) rather
# than just these files.
sed -i '/^`timescale /d' "$DST_DIR"/*.v

# Some files of Dynamatic's RTL library do not end with a newline. Besides
# Verilator's EOFNEWLINE lint, Verilator (5.040) then ignores the file-scoped
# waivers of dot_product.vlt for the declarations in those files, so the
# missing newline is added.
sed -i -e '$a\' "$DST_DIR"/*.v

HLS_FILES=$(cd "$DST_DIR" && ls ./*.v | sed 's#^\./##' | sort | sed 's/^/    - rtl\/hls\//')

cat >"$CORE_FILE" <<EOF
CAPI=2:

# Auto-generated by generate_core.sh -- do not edit by hand.
# Regenerate with:
#   ./generate_core.sh
# (Dynamatic runs in Docker by default; see ../dynamatic.sh.)

name: "epfl:ip:dot_product_dynamatic"
description: "Dynamatic-generated dot-product circuit with its X-HEEP adapter (operand fetch into local RAMs + CTRL register file)."

filesets:
  files_rtl:
    depend:
    - pulp-platform.org::axi
    - x-heep:ip:dot_product_ctrl
    files:
$HLS_FILES
    - rtl/dot_product_operand_buffer.sv
    - rtl/dot_product_hls_adapter.sv
    file_type: systemVerilogSource

  verilator-waiver:
    files:
    - dot_product.vlt
    file_type: vlt

targets:
  default:
    filesets:
    - files_rtl
    - tool_verilator ? (verilator-waiver)
EOF

n_files=$(echo "$HLS_FILES" | wc -l)
echo "Generated $CORE_FILE: ${n_files} Dynamatic RTL file(s) + adapter, from $WORK_DIR/."
